source 'https://rubygems.org'

gem 'active_model_serializers', '~> 0.10.4'
gem 'devise', '~> 4.2'
gem 'kaminari', '~> 1.0.1'
gem 'mysql2', '~> 0.4.5'
gem 'rails', '~> 5.0.1'
gem 'tiddle', '~> 1.0'
gem 'rack-cors', '~> 0.4.0', require: 'rack/cors'

group :development do
  gem 'listen', '~> 2.9'
  gem 'spring', '~> 2.0'
end

group :development, :test do
	gem 'factory_girl_rails', '~> 4.8'
  gem 'faker', '~> 1.7', '>= 1.7.2'
  gem 'rspec-rails', '~> 3.5'
end

group :test do
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.1'
  gem 'rspec-json_expectations', '~> 2.1'
  gem 'simplecov', require: false
end
