source 'https://rubygems.org'


gem 'rails', '~> 5.0.1'
gem 'mysql2', '~> 0.4.5'
gem 'devise', '~> 4.2'
gem 'tiddle', '~> 1.0'

group :development do
	gem 'spring', '~> 2.0'
	gem 'listen', '~> 2.9'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'faker', '~> 1.7', '>= 1.7.2'
end