source 'https://rubygems.org'


gem 'rails', '~> 5.0.1'
gem 'mysql2', '~> 0.4.5'
gem 'devise', '~> 4.2'
gem 'tiddle', '~> 1.0'
gem 'active_model_serializers', '~> 0.10.4'
gem 'kaminari', '~> 1.0'

group :development do
	gem 'spring', '~> 2.0'
	gem 'listen', '~> 2.9'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'faker', '~> 1.7', '>= 1.7.2'
end

group :test do
	gem 'simplecov', :require => false
	gem 'rails-controller-testing', '~> 1.0', '>= 1.0.1'
	gem 'rspec-json_expectations', '~> 2.1'
	gem 'factory_girl_rails', '~> 4.8'
end